### ISSUE TITLE
Document use with Reverse proxies

### ISSUE THREAD

**Issue by andyquinterom** [ixpantia/faucet#25]
Document how to use with Nginx and Apache

**Comment by CharlesBordet** [comment]
I have been able to configure a nginx reverse proxy thanks to the documentation.

However, it wasn't "enough" and I was receiving this error from the faucet logs:

```
2024-07-15T09:11:30Z ERROR faucet_server::client::websockets] upgrade error: Hyper error: hyper::Error(User(NoUpgrade))
```

I added `proxy_http_version 1.1` and it resolved the issue. Maybe this could be added to the documentation? 

I'm sending a Pull Request but it lacks an explanation as I don't understand fully why this is needed. From what I read in the [nginx documentation](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version), is this related to keepalive connections and websockets?

**Comment by andyquinterom** [comment]
Add Google Cloud Run example
